sudo: required

language: cpp
compiler:
- gcc
# - clang


install: sudo apt-get install make autoconf automake cmake g++ git libbz2-dev libsnappy-dev libssl-dev libtool make pkg-config python3 python3-jinja2 doxygen libncurses5-dev libreadline-dev perl

script:
- sh ciscripts/installboost.sh
- sh ciscripts/installboost.sh