dist: xenial

language: cpp
compiler:
 - gcc


addons:
  apt:
    packages:
    - autoconf
    - automake
    - cmake
    - g++
    - git
    - libbz2-dev
    - libsnappy-dev
    - libssl-dev
    - libtool
    - make
    - pkg-config
    - python3
    - python3-jinja2
    - libboost-chrono-dev
    - libboost-context-dev
    - libboost-coroutine-dev
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-iostreams-dev
    - libboost-locale-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libboost-signals-dev
    - libboost-system-dev
    - libboost-test-dev
    - libboost-thread-dev
    - lcov

before_install:
  - gem install mtime_cache

jobs:
  include:
  - stage: prepare cache
    script:
      - |
        if [ timeout 1800 sh ciscripts/compiletest.sh ] ; then sh ciscripts/collectcoverage.sh ; fi
        exit 0

cache:
  directories:
  - build
  - .mtime_cache
  - ~/.ccache