sudo: required

language: cpp
compiler:
- gcc
# - clang


addons:
  apt:
    packages:
      - pv
      - make
      - autoconf
      - automake
      - cmake
      - g++
      - git
      - libbz2-dev
      - libsnappy-dev
      - libssl-dev
      - libtool
      - make
      - pkg-config
      - python3
      - python3-jinja2
      - doxygen
      - libncurses5-dev
      - libreadline-dev
      - perl

script:
- sh ciscripts/installboost.sh
- sh ciscripts/compiletest.sh

jobs:
  include:
  - stage: prepare cache
    script:
      - sh ciscripts/installboost.sh
      - sh ciscripts/compiletest.sh
  - stage: test
    script: ls -al .
  - stage: test
    script: ls -al build
  - stage: test
    script: ls -al build/*

cache:
  apt: true
  directories:
  - $HOME/opt/boost_1_60_0
  - boost_1_60_0
  - build