FROM phusion/baseimage:0.9.19

ENV LANG=en_US.UTF-8

RUN \
    apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        cmake \
        doxygen \
        gdb \
        git \
        libboost-all-dev \
        libyajl-dev \
        libreadline-dev \
        libssl-dev \
        libtool \
        liblz4-tool \
        ncurses-dev \
        pkg-config \
        python3 \
        python3-dev \
        python3-jinja2 \
        python3-pip \
        nginx \
        fcgiwrap \
        awscli \
        jq \
        wget \
        virtualenv \
        gdb \
        libgflags-dev \
        libsnappy-dev \
        zlib1g-dev \
        libbz2-dev \
        liblz4-dev \
        libzstd-dev \
        lcov \
        ruby \
        ccache \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip3 install gcovr && \
    gem install mtime_cache



RUN cd /usr/local/src/steem && git submodule update --init --recursive && sh ciscripts/compiletest.sh

RUN if [ "$BUILD_STEP" = "1" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem/build && \
    ./tests/chain_test ; \
    fi

RUN if [ "$BUILD_STEP" = "2" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem/build && \
    ./tests/plugin_test ; \
    fi

RUN if [ "$BUILD_STEP" = "3" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem/build && \
    ./programs/util/test_fixed_string ; \
    fi

RUN if [ "$BUILD_STEP" = "4" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem && \
    programs/build_helpers/get_config_check.sh ; \
    fi

RUN if [ "$BUILD_STEP" = "5" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem && \
    doxygen && \
    PYTHONPATH=programs/build_helpers \
    python3 -m steem_build_helpers.check_reflect ; \
    fi

RUN if [ "$BUILD_STEP" = "6" ] || [ ! "$BUILD_STEP" ] ; then \
    cd /usr/local/src/steem && \
    sh ciscripts/collectcoverage.sh ; \
    fi