version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci .
        no_output_timeout: 30m
    - save_cache:
        key: source-v2-{{ .Branch }}-{{ .Revision }}
        paths:
        - build
        - .mtime_cache
        - ~/.ccache
