version: 2

jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: |
          docker build -f Dockerfile_ci --build-arg BUILD_STEP=8 -t=steem .
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/build) - $(basename /usr/local/src/steemtmp/build) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/.mtime_cache) - $(basename /usr/local/src/steemtmp/.mtime_cache) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/.ccache) - $(basename /usr/local/src/steemtmp/.ccache) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steem/coverage.info) - $(basename /usr/local/src/steemtmp/coverage.info) | tar Cxf $HOME/project -
          wget -O - https://codecov.io/bash | bash || echo "Codecov did not collect coverage reports"
        no_output_timeout: 30m
    - save_cache:
        key: source-v2-{{ .Branch }}-{{ .Revision }}
        paths:
        - build
        - .mtime_cache
        - .ccache
