version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v1-{{ .Branch }}-{{ .Revision }}
        - source-v1-{{ .Branch }}-
        - source-v1-
    - run:
        name: Compile cache
        command: docker build ciscripts
        no_output_timeout: 30m
    - save_cache:
        key: source-v1-{{ .Branch }}-{{ .Revision }}
        paths:
        - build
        - .mtime_cache
        - ~/.ccache
