version: 2

jobs:
  complete:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - complete-v2-{{ .Branch }}-{{ .Revision }}
        - complete-v2-{{ .Branch }}-
        - complete-v2-
    - run:
        name: Compile cache
        command: |
          docker build -f Dockerfile_ci --build-arg BUILD_STEP=8 -t=steem .
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/build) - $(basename /usr/local/src/steemtmp/build) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/.mtime_cache) - $(basename /usr/local/src/steemtmp/.mtime_cache) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/.ccache) - $(basename /usr/local/src/steemtmp/.ccache) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steemtmp/coverage.info) - $(basename /usr/local/src/steemtmp/coverage.info) | tar Cxf $HOME/project -
          wget -O - https://codecov.io/bash | bash || echo "Codecov did not collect coverage reports"
        no_output_timeout: 30m
    - save_cache:
        key: complete-v2-{{ .Branch }}-{{ .Revision }}
        paths:
        - build
        - .mtime_cache
        - .ccache
  build:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: |
          docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=8 -t=steem .
          docker run steem tar Ccf $(dirname /usr/local/src/steem/build) - $(basename /usr/local/src/steem/build) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steem/.mtime_cache) - $(basename /usr/local/src/steem/.mtime_cache) | tar Cxf $HOME/project -
          docker run steem tar Ccf $(dirname /usr/local/src/steem/.ccache) - $(basename /usr/local/src/steem/.ccache) | tar Cxf $HOME/project -
        no_output_timeout: 30m
    - save_cache:
        key: source-v2-{{ .Branch }}-{{ .Revision }}
        paths:
        - build
        - .mtime_cache
        - .ccache

  chain_test:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=1 .
        no_output_timeout: 30m

  plugin_test:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=2 .
        no_output_timeout: 30m

  test_fixed_string:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=3 .
        no_output_timeout: 30m

  get_config_check:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=4 .
        no_output_timeout: 30m

  doxygen:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=5 .
        no_output_timeout: 30m

  coverage:
    machine: true
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init --recursive
    - restore_cache:
        keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-
    - run:
        name: Compile cache
        command: |
          docker build -f Dockerfile_ci_fanout --build-arg BUILD_STEP=6 -t=steem .
          docker run steem tar Ccf $(dirname /usr/local/src/steem/coverage.info) - $(basename /usr/local/src/steem/coverage.info) | tar Cxf $HOME/project -
          wget -O - https://codecov.io/bash | bash || echo "Codecov did not collect coverage reports"
        no_output_timeout: 30m

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
    - complete
    - build
    - chain_test:
        requires:
        - build
    - plugin_test:
        requires:
        - build
    - test_fixed_string:
        requires:
        - build
    - get_config_check:
        requires:
        - build
    - doxygen:
        requires:
        - build
    - coverage:
        requires:
        - chain_test
        - plugin_test
        - test_fixed_string
        - get_config_check
        - doxygen