version: 2
jobs:
  build:
    docker:
    - image: ubuntu:16.04
    steps:
    - checkout
    - run:
        name: Greeting
        command: echo Hello, world.
    - run:
        name: Print the Current Time
        command: sudo apt-get update && sudo apt-get install -y autoconf \
          automake \
          cmake \
          g++ \
          git \
          libbz2-dev \
          libsnappy-dev \
          libssl-dev \
          libtool \
          make \
          pkg-config \
          python3 \
          python3-jinja2 \
          libboost-chrono-dev \
          libboost-context-dev \
          libboost-coroutine-dev \
          libboost-date-time-dev \
          libboost-filesystem-dev \
          libboost-iostreams-dev \
          libboost-locale-dev \
          libboost-program-options-dev \
          libboost-serialization-dev \
          libboost-signals-dev \
          libboost-system-dev \
          libboost-test-dev \
          libboost-thread-dev \
          doxygen \
          libncurses5-dev \
          libreadline-dev \
          perl \
          lcov